version: '3.8'

services:
  # Memorizer application
  memorizer:
    build:
      context: .
      dockerfile: src/Memorizer/Dockerfile
    container_name: memorizer-app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Storage: Host=postgres;Port=5432;Database=postgmem;Username=postgres;Password=postgres
      
      MEMORIZER_Embeddings__Type: Custom
      MEMORIZER_Embeddings__ApiUrl: http://192.168.0.50:1234
      MEMORIZER_Embeddings__Model: text-embedding-all-minilm-l12-v2      
      
      MEMORIZER_LLM__Type: Custom
      MEMORIZER_LLM__ApiUrl: http://192.168.0.50:1234
      MEMORIZER_LLM__Chunking__MinCharactersForChunking: '2000'
      MEMORIZER_LLM__Chunking__TargetChunkSize: '1500'
      MEMORIZER_LLM__Model: openai/gpt-oss-20b
      MEMORIZER_LLM__Timeout: 00:02:00      
      
      Neo4j__Uri: bolt://neo4j:7687
      Neo4j__User: neo4j
      Neo4j__Password: password
      Neo4j__Database: neo4j
      MEMORIZER_Server__CanonicalUrl: http://localhost:5000
      MEMORIZER_Server__UserName: admin
      MEMORIZER_Server__Password: admin123
      MEMORIZER_Server__ApiKey: your-api-key-here
    ports:
      - "5000:8080"        
    labels:
      io.rancher.scheduler.affinity:host_label: server=latemain