<Project>
  <PropertyGroup>
    <Copyright>© $([System.DateTime]::Now.Year)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/dariogriffo/postg-mem</PackageProjectUrl>
    <VersionPrefix>1.2.7</VersionPrefix>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <Deterministic>true</Deterministic>
    <PackageReleaseNotes>- [Multi-modal LLM service OpenAI extension - Separate MultiModalService into Custom/OpenAI two implementations, add MultiModalOpenAIService based on OpenAI SDK, select implementation by Type in configuration files]</PackageReleaseNotes>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>